services:
  frontend:
    build: /Users/uchennanwagbara/Documents/Personal Projects/ChennaFlix/frontend
    image: chennaflix-frontend:latest
    container_name: chennaflix-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: /Users/uchennanwagbara/Documents/Personal Projects/ChennaFlix/backend
    image: chennaflix-backend:latest
    container_name: chennaflix-backend
    volumes:
      - /Users/uchennanwagbara/Documents/Personal Projects/ChennaFlix/backend/src/main:/app/src/main
      - /Users/uchennanwagbara/Documents/Personal Projects/ChennaFlix/backend/target:/app/target  
    ports:
      - "8000:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres?currentSchema=angular_resume
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: chennaflix-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dudecool01
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data 
      - /Users/uchennanwagbara/Documents/Personal Projects/ChennaFlix/backend/db-init:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
