name: Build and Push Docker Images

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }} 

      # Step 4: Build the backend JAR using Maven
      - name: Build Backend JAR with Maven
        run: |
          cd backend  # Navigate to backend directory where pom.xml is located
          mvn package -DskipTests

      # Step 5: Build and push backend Docker image
      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: ./backend  
          push: true  
          tags: uchenna23/chennaflix-backend:latest 
      # Step 6: Build and push frontend Docker image
      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend  
          push: true 
          tags: uchenna23/chennaflix-frontend:latest 
